[package]
name = "quickhash"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"

[dependencies]
siphasher = "0.3.0"
crossbeam-channel = "0.3.8"
num_cpus = "1.10.0"
crossbeam-utils = "0.6.5"
